# image must have JDK8+, gradle, curl, unzip
image: maven:3.3.9-jdk-8
   

stages:
  - Build_SCA
  - Veracode_Static

SCA_Scan:
  stage: Build_SCA
  script:
    - mvn -B package --file pom.xml
  artifacts:
    paths:
    - target/verademo.war
    expire_in: 1 week
   
  after_script:
    - curl -sSL https://download.sourceclear.com/ci.sh | sh
  

Pipeline Scan:
  stage: Veracode_Static
  dependencies:
    - SCA_Scan
  script:
    - curl -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
    - unzip pipeline-scan-LATEST.zip pipeline-scan.jar
    - java -jar pipeline-scan.jar
      --veracode_api_id "${VERACODE_API_ID}"
      --veracode_api_key "${VERACODE_API_SECRET}"
      --file "target/verademo.war"
      --project_name "${CI_PROJECT_PATH}"
      --project_url "${CI_REPOSITORY_URL}"
      --project_ref "${CI_COMMIT_REF_NAME}"
      --fail_on_severity="Very High, High"
      --fail_on_cwe="80"
      
   

Policy Scan:
  stage: Veracode_Static
  dependencies:
    - SCA_Scan
  script:

    - VERACODE_WRAPPER_VERSION=$(curl -sS "https://search.maven.org/solrsearch/select?q=g:%22com.veracode.vosp.api.wrappers%22&rows=20&wt=json" | jq -r '.response.docs[0].latestVersion') && curl -sS -o veracode-wrapper.jar "https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/${VERACODE_WRAPPER_VERSION}/vosp-api-wrappers-java-${VERACODE_WRAPPER_VERSION}.jar"
    - java -jar veracode-wrapper.jar -vid ${VERACODE_API_ID} -vkey ${VERACODE_API_SECRET} -action UploadAndScan -appname "verademo-java" -createprofile false -autoscan true -filepath "target/verademo.war" -version "job ${CI_JOB_ID} in pipeline ${CI_PIPELINE_ID}" -sandboxname "Gitlab" -createsandbox true -autoscan true

