# This is a sample build configuration for Java (Maven).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
  default:
    - step:
       name: Maven Build
       script: # Modify the commands below to build your repository.
          - mvn -B package --file pom.xml # -B batch mode makes Maven less verbose
       artifacts: # defining the artifacts to be passed to each future step.
                 - target/**
    - step:
       name: Veracode SCA Agent Scan
       script: 
          - curl -sSL https://download.sourceclear.com/ci.sh | bash -s – scan --debug 

    - step:
       name: Veracode Pipeline Scan
       script:
        - curl -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
        - unzip pipeline-scan-LATEST.zip
        - java -Dpipeline.debug=true -jar pipeline-scan.jar --veracode_api_id "$VERACODE_API_ID" --veracode_api_key "$VERACODE_API_KEY" --file "target/verademo.war" --fail_on_severity="Very High, High" 



    - step:
        name: Veracode Policy Scan
        script:
         - VERACODE_WRAPPER_VERSION=$(curl -sS "https://search.maven.org/solrsearch/select?q=g:%22com.veracode.vosp.api.wrappers%22&rows=20&wt=json" | jq -r '.response.docs[0].latestVersion') && curl -sS -o veracode-wrapper.jar "https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/${VERACODE_WRAPPER_VERSION}/vosp-api-wrappers-java-${VERACODE_WRAPPER_VERSION}.jar"
         - java -jar veracode-wrapper.jar -vid $VERACODE_API_ID -vkey $VERACODE_API_KEY
                        -action uploadandscan -appname "verademo-java" -filepath "target/verademo.war"
                        -createprofile false -version "commit $GITHUB_SHA_SHORT step $BITBUCKET_STEP_UUID run $BITBUCKET_PIPELINE_UUID"
                        -sandboxname "Bitbucket" -createsandbox false -autoscan true
